POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"admin",
    "password":"123456789"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"nghia1",
    "password":"123456789"
}
###
POSt http://localhost:5000/post/addPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjIxN2VkY2E0OGFlM2VmNjFjNzJiOWQiLCJpYXQiOjE2NDYzNjUzMTV9.rYOfP7JkTbGaHD6oMwByR2FG-1Pa2WhXIbUOky-NMt4

{
    "title":"title",
    "description":"description",
    "url":"google.com"
}
###
GET http://localhost:5000/post/listPost


###
GET http://localhost:5000/post/getPost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjIxN2VkY2E0OGFlM2VmNjFjNzJiOWQiLCJpYXQiOjE2NDYzNjUzMTV9.rYOfP7JkTbGaHD6oMwByR2FG-1Pa2WhXIbUOky-NMt4

###
PUT http://localhost:5000/post/updatePost/61dd53b575f691f59c6d870a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjIxN2VkY2E0OGFlM2VmNjFjNzJiOWQiLCJpYXQiOjE2NDYzNjUzMTV9.rYOfP7JkTbGaHD6oMwByR2FG-1Pa2WhXIbUOky-NMt4

{
    "title":"ab",
    "description":"test",
    "url":"google.com"
}

###
DELETE  http://localhost:5000/post/deletePost/62218aac93b566b3c1713d56
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjIxN2VkY2E0OGFlM2VmNjFjNzJiOWQiLCJpYXQiOjE2NDYzNjUzMTV9.rYOfP7JkTbGaHD6oMwByR2FG-1Pa2WhXIbUOky-NMt4
