POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"admin",
    "password":"123456789"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"123456789"
}
###
POSt http://localhost:5000/post/addPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5YzZmMWEyYjNjZmQzYTNmY2U1ZmQiLCJpYXQiOjE2NDc3NDYzNjF9.59TvOP-CKdf27EjCgkanbiV3ZNrrB9cqgImCf9NgrKY

{
    "title":"title4",
    "description":"description",
    "image":"cdvfghjh",
    "urlDemo":"google.com",
    "urlSource":"google.com"
}
###
GET http://localhost:5000/post/listPost


###
GET http://localhost:5000/post/getPost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5YzZmMWEyYjNjZmQzYTNmY2U1ZmQiLCJpYXQiOjE2NDY5MDUwODZ9.5VevSbHBJJjqNTaOxKumkhjKKj7tcwCwJ5zBT_zZdDo

###
PUT http://localhost:5000/post/updatePost/6229c83b3373194860cc0c3b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5YzZmMWEyYjNjZmQzYTNmY2U1ZmQiLCJpYXQiOjE2NDY5MDUwODZ9.5VevSbHBJJjqNTaOxKumkhjKKj7tcwCwJ5zBT_zZdDo

{
    "title":"title 1",
    "description":"description",
    "image":"image",
    "urlDemo":"google.com",
    "urlSource":"google.com"
}

###
DELETE  http://localhost:5000/post/deletePost/6229c83b3373194860cc0c3b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI5YzZmMWEyYjNjZmQzYTNmY2U1ZmQiLCJpYXQiOjE2NDY5MDUwODZ9.5VevSbHBJJjqNTaOxKumkhjKKj7tcwCwJ5zBT_zZdDo
