export { default as Navbar } from './Navbar/Navbar.jsx'
export { default as Hero } from './Hero/Hero.jsx'
export { default as About } from './About/About.jsx'
export { default as Skills } from './Skills/Skills.jsx'
export { default as Portfolio } from './Portfolio/Portfolio.jsx'
export { default as Contact } from './Contact/Contact.jsx'
export { default as Footer } from './Footer/Footer.jsx'